name: With server
on:
  pull_request: {
    types: [labeled, opened, edited]
  }
jobs:
  cypress-run:
    if: contains(github.event.pull_request.labels.*.name, 'request:cypress')
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run storybook
          wait-on: 'http://localhost:6006'
